### ISSUE TITLE
Repository "Monitoring the spread of COVID-19 by estimating reproduction numbers over time"

### ISSUE THREAD

**Issue by stefanheyder** [timueh/sars-cov2-modelling-initiative#10]
Hallo,

gerne würden wir unseren Code zur Schätzung der Reproduktionszahl in Deutschland (und anderen Ländern) beisteuern. Das Repository ist unter https://github.com/Stochastik-TU-Ilmenau/COVID-19 zu finden - **Achtung**: der Code ist im branch `gh-pages` (nicht `master`), da wir ihn gleichzeitig benutzen um auf Github eine täglich aktualisierte Seite zu hosten (https://stochastik-tu-ilmenau.github.io/COVID-19/germany.html). 

Die Programmiersprache ist **R**, als E-Mail Adresse bitte thomas.hotz@tu-ilmenau.de eintragen.

**Comment by timueh** [comment]
Wunderbar! Ich kümmere mich drum. Danke für den wertvollen Kommentar mit dem Branch.

**Comment by stefanheyder** [comment]
Vielen Dank für die Mühen!
