### ISSUE TITLE
Ist das jetzt das richtige procedere?

### ISSUE THREAD

**Issue by k1dehner** [timueh/sars-cov2-modelling-initiative#9]
Python
https://github.com/k1dehner/sars-cov2-modelling-initiative 
kh.dehner@gmx.de

**Comment by timueh** [comment]
Grundsätzlich ja, aber das repository gibt es ja gar nicht?!...

**Comment by k1dehner** [comment]
Hallo Tillmann,

 


ich habe das Repository mit den Default-Einstellungen angelegt. Ich bekomme es nur zu sehen, wenn ich mich auf GitHub eingeloggt habe. Liegt es daran, dass ich das Repository nicht public gemacht habe (siehe Screenshot)?


Ich habe noch keine Änderungen hochgeladen (commited oder gepusht oder sonstwie?), sondern möchte das Modell jetzt einfach stehen lassen und ein neues Modell entwickeln, zuerst die Modellierung skizzieren und beschreiben (am besten nach IMRAD-Schema) und dann den Python-Code. Wie mache ich das am besten?
Lege ich dafür einen neuen Folder (model2 o.ä) an? Wenn mir ein ordentliches pdf für die Beschreibung gelingt, kann ich das dann auch auf GitHub hochladen? Oder gibt es andere Möglichkeiten, solche Dokumente auch ohne eigene Website  ins Netz zu stellen?

 

Beste Grüße
 

 

Gesendet: Montag, 27. April 2020 um 15:58 Uhr
Von: "Tillmann Muehlpfordt" <notifications@github.com>
An: "timueh/sars-cov2-modelling-initiative" <sars-cov2-modelling-initiative@noreply.github.com>
Cc: "k1dehner" <kh.dehner@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [timueh/sars-cov2-modelling-initiative] Ist das jetzt das richtige procedere? (#9)


 

Grundsätzlich ja, aber das repository gibt es ja gar nicht?!...

**Comment by timueh** [comment]
> ich habe das Repository mit den Default-Einstellungen angelegt. Ich bekomme es nur zu sehen, wenn ich mich auf GitHub eingeloggt habe. Liegt es daran, dass ich das Repository nicht public gemacht habe (siehe Screenshot)?

es muss ein public repository sein, damit jeder darauf zugreifen kann, ja.

Grundsätzlich kann in ein github repository alles hochgeladen werden, also ja. genau für den zweck, den du beschreibst, gibt es git: man hat code in einer version, arbeitet dann weiter daran, dokumentiert ihn und lädt ihn dann hoch.

**Comment by k1dehner** [comment]
o.k., ich habe noch Mühe mich mit GitHub anzufreunden. Für den Anfang brauche ich keine Versionsverwaltung, das wird mir zu kompliziert, da arbeite ich besser auf meinem lokalen Verzeichnis. Das Repository auf GitUHub habe ich deswegen erst einmal gelöscht. Weenn ich meine Ergebnisse in die Reihe gebracht habe, werde ich sie in ein neues Repository laden und das public machen.

 

Ein issue stellt, wie ich inzwischen gelernt habe, eine Art Mitteilung dar, die sich ii.d.R. auf das Repostory bezieht. Mein issue ist nun aber eigentlich gegenstandslos. Lässt sich das sich das Ding irgendiwe aus der Welt schaffen?

Dann hängt da auch noch der failed pull request, lässt sich das eventuell noch in Ordnung bringen?  

 
 

Gesendet: Dienstag, 28. April 2020 um 10:19 Uhr
Von: "Tillmann Muehlpfordt" <notifications@github.com>
An: "timueh/sars-cov2-modelling-initiative" <sars-cov2-modelling-initiative@noreply.github.com>
Cc: "k1dehner" <kh.dehner@gmx.de>, "State change" <state_change@noreply.github.com>
Betreff: Re: [timueh/sars-cov2-modelling-initiative] Ist das jetzt das richtige procedere? (#9)


 


ich habe das Repository mit den Default-Einstellungen angelegt. Ich bekomme es nur zu sehen, wenn ich mich auf GitHub eingeloggt habe. Liegt es daran, dass ich das Repository nicht public gemacht habe (siehe Screenshot)?


es muss ein public repository sein, damit jeder darauf zugreifen kann, ja.

Grundsätzlich kann in ein github repository alles hochgeladen werden, also ja. genau für den zweck, den du beschreibst, gibt es git: man hat code in einer version, arbeitet dann weiter daran, dokumentiert ihn und lädt ihn dann hoch.
